name: build-release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "x86_64-unknown-linux-musl,aarch64-unknown-linux-musl"
      - name: build
        run: cargo build --release
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/x86_64-unknown-linux-musl/rustc-stress,target/aarch64-unknown-linux-musl/rustc-stress"
          makeLatest: "legacy"
