name: build-release

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pkgver: ${{ steps.set_var.outputs.pkgver }}
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set pkgver env var
        run: |
          echo "pkgver=$(cat Cargo.toml | grep 'version' | head -n 1 | cut -d'"' -f2)" >> $GITHUB_OUTPUT
      - name: install rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}
      - name: build
        run: cargo build --release --target ${{ matrix.target }}
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustc-stress-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/rustc-stress
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: rustc-stress-*

      - name: show structure
        run: ls -R
      # - name: create release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: artifacts/*
      #     tag_name: v${{ needs.build.outputs.pkgver }}
      #     make_latest: true
          
